# -*- coding: utf-8 -*-
"""Hospitals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8EkP_fJjUmtIZLwQLs40vNfO03UhUD0
"""

from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

driver=webdriver.Chrome(executable_path='/Users/ayushigupta/Downloads/chromedriver')

driver.get('http://people.dbmi.columbia.edu/~friedma/Projects/DiseaseSymptomKB/index.html')

btn=driver.find_element_by_tag_name('table')
btn

btn.text

columns=['Disease','chest pain','shortness of breath','dizziness','sweat','tiredness','unresponsiveness',
    'vomiting','feeling suicidal','sleeplessness','blackout','cough',
   'fever','wheezing','diarrhea','difficulty passing urine','nausea']

data={'Disease':['Hypertension','Diabetes','Depression','Heart disease','pneumonia','asthma','infection','urinary infection','corona','dehydration'],
     'chest pain':[1,1,0,1,0,0,0,0,0,0],
     'shortness of breath':[1,1,0,1,1,1,0,0,1,0],
     'dizziness':[1,0,0,0,0,0,0,0,0,1],
     'sweat':[1,1,0,1,0,0,0,0,0,0],
     'tiredness':[0,0,0,0,0,1,0,0,1,1],
     'unresponsiveness':[0,1,0,0,0,0,0,0,0,0],
     'vomiting':[0,1,0,0,0,1,0,0,0,1],
     'feeling suicidal':[0,0,1,0,0,0,0,0,0,0],
     'sleeplessness':[0,0,1,0,0,0,0,0,0,0],
     'blackout':[0,0,1,0,0,0,0,0,0,1],
     'cough':[0,0,0,0,1,1,0,0,1,0],
     'fever':[0,0,0,0,1,0,1,1,1,1],
     'wheezing':[0,0,0,0,1,1,0,0,0,0],
     'diarrhea':[0,0,0,0,0,0,1,0,0,1],
     'difficulty passing urine':[0,0,0,0,0,0,0,1,0,0],
     'nausea':[1,1,0,0,0,0,0,0,0,1]}

df=pd.DataFrame(data,columns=columns)

df

def function():
    li=['Disease']
    n=int(input())
    for i in range(n):
        symp=input()
        li.append(symp)

    df2=df[li]   
    #print(df2)
    maxi=0
    for i in range(df.shape[0]):
        count=0
        for j in range(1,df2.shape[1]):
            if(df2.iloc[i,j]==1):
                count+=1
        #print(df2.iloc[i,0],count)
        if(count>maxi):
            maxi=count
            recom=df2.iloc[i,0]
    return (recom)

function()

